/// @file
/// @author Emil VATAI <emil.vatai@gmail.com>
/// @date 2019-11-11

#include <cassert>
#include <fstream>
#include <iostream>
#include <mpi.h>
#include <string>
#include <unistd.h>

#include "args.h"
#include "buffers.h"
#include "utils.hpp"

/// @page pdmpk_exec pdmpk_exec
///
/// The body of `pdmpk_exec` page.

/// Execute the buffers generated by @ref Buffers::Load.
int main(int argc, char *argv[]) {
  int rank, npart;
  MPI_Init(&argc, &argv);
  MPI_Comm_size(MPI_COMM_WORLD, &npart);
  MPI_Comm_rank(MPI_COMM_WORLD, &rank);
  const Args args(argc, argv);
  assert(npart == args.npart);

  // MPI debuging:
  // - start with: $ gdb pdmpk_exec PID
  // - up # go up in the stack
  // - up # two times
  // - set var i = 1
  // - continue
  // if (rank == 3) {
  //   int i = 1;
  //   std::cout << "PID " << getpid() << " ready for attach" << std::endl;
  //   while (0 == i)
  //     sleep(5);
  // }

  Buffers buf(args);
  buf.Load(rank);
  buf.DbgCheck();
  buf.LoadInput();
  buf.Exec();

  buf.DumpMbufTxt(rank);

  buf.results.FillVal(buf.mbuf);
  buf.results.Dump(rank);
  buf.results.DumpTxt(rank);

  MPI_Finalize();

  std::cout << argv[0] << ": process " << rank << " for " << args.mtxname
            << " finished" << std::endl;
  return 0;
}
