sudo: false
language: cpp
dist: bionic
compiler: gcc

branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen
      - libopenmpi-dev

script:
  - wget http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/metis-5.1.0.tar.gz
  - tar xzf metis-5.1.0.tar.gz
  - cd metis-5.1.0
  - make config
  - make
  - sudo make install
  - mkdir ../build
  - cd ../build
  - cmake ..
  - cmake --build .

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build/docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master

before_install:
  - test -n $CC && unset CC
