sudo: false

branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen

script:
  - cd pdmpk
  - doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: pdmpk/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master