sudo: false

branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen
      - libopenmpi-dev

script:
  - mkdir build
  - cd build
  - cmake ../pdmpk
  - cmake --build .

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master

before_install:
  - test -n $CC && unset CC