// This is a matrix generator file. No compuation is performed here.
// Version2: generates values and diagonal elements
//
// Usage/IMPORTANT NOTE: gpmetis uses the format generated by the
// original gen program! :'( However gen2 can be used without much
// problems simply by rewriting g0 in the directory generated by
// driver.
//
// gen and gen2 use different for the edges (because I wanted to clean
// things up) but it shouldn't be a problem.

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>

int main(int argc, char **argv) {
  printf("Important notice: use the original gen program, because metis "
         "does not understand loops.  So use first gen, then copy over "
         "the g0 file in the directory generated by ./driver\n\n");
  if (argc != 4) {
  usage:
    fprintf(stderr, "usage: %s type size ghead\n", argv[0]);
    fprintf(stderr, "type: m5p m7p m9p t5p t7p t9p cube\n");
    exit(1);
  }

  int size = -1;
  sscanf(argv[2], "%d", &size);
  if (size <= 0) {
    fprintf(stderr, "cannot get size (%d)\n", size);
    goto usage;
  }

  char s[10 + strlen(argv[3])];
  sprintf(s, "%s.g0", argv[3]);
  FILE *f = fopen(s, "w");
  if (f == NULL) {
    fprintf(stderr, "cannot open %s\n", s);
    goto usage;
  }

  sprintf(s, "%s.val", argv[3]);
  FILE *fv = fopen(s, "w");
  if (fv == NULL) {
    fprintf(stderr, "cannot open %s\n", s);
    goto usage;
  }

  sprintf(s, "%s.co", argv[3]);
  FILE *fp = fopen(s, "w");
  if (f == NULL) {
    fprintf(stderr, "Cannot open %s\n", s);
    goto usage;
  }

  int n = size;

  if (strcmp(argv[1], "m5p") == 0) {
    fprintf(f, "%d %d\n", n * n, 2 * (n-1) * n + n * n);

    int i, j;
    for (i=0; i< n; i++)
      for (j=0; j< n; j++) {
        double mid = -4;
        double side = 1;
	if (i > 0) {
	  fprintf(f, "%d ", (i-1) * n + j + 1);
          fprintf(fv, "%lf ", side);
        }
	if (j > 0) {
	  fprintf(f, "%d ", i * n + j-1 + 1);
          fprintf(fv, "%lf ", side);
        }
        fprintf(f, "%d ", i * n + j + 1);
        fprintf(fv, "%lf ", mid);
	if (j < n-1) {
	  fprintf(f, "%d ", i * n + j+1 + 1);
          fprintf(fv, "%lf ", side);
        }
	if (i < n-1) {
	  fprintf(f, "%d ", (i+1) * n + j + 1);
          fprintf(fv, "%lf ", side);
        }
	fprintf(f, "\n");

	fprintf(fp, "%d %d\n", i, j);
      }

  } else if (strcmp(argv[1], "t5p") == 0) {
    fprintf(f, "%d %d\n", n * n, 3 * n * n);

    int i, j;
    for (i=0; i< n; i++)
      for (j=0; j< n; j++) {
        double mid = -4;
        double side = 1;
        if (i == n - 1) {
	  fprintf(f, "%d ", 0 * n + j + 1);
          fprintf(fv, "%lf ", side);
        }
	if (i > 0) {
	  fprintf(f, "%d ", (i-1) * n + j + 1);
          fprintf(fv, "%lf ", side);
        }
        if (j == n - 1){
	  fprintf(f, "%d ", i * n + 0 + 1);
          fprintf(fv, "%lf ", side);
        }
	if (j > 0) {
	  fprintf(f, "%d ", i * n + j-1 + 1);
          fprintf(fv, "%lf ", side);
        }

        fprintf(f, "%d ", i * n + j + 1);
        fprintf(fv, "%lf ", mid);

        if (i < n - 1) {
	  fprintf(f, "%d ", (i+1) * n + j + 1);
          fprintf(fv, "%lf ", side);
        }
	if (j < n - 1) {
	  fprintf(f, "%d ", i * n + j+1 + 1);
          fprintf(fv, "%lf ", side);
        }
        if (i == 0) {
	  fprintf(f, "%d ", (n-1) * n + j + 1);
          fprintf(fv, "%lf ", side);
        }
        if (j == 0){
	  fprintf(f, "%d ", i * n + n-1 + 1);
          fprintf(fv, "%lf ", side);
        }
	fprintf(f, "\n");

	fprintf(fp, "%d %d\n", i, j);
      }

  } else if (strcmp(argv[1], "m7p") == 0) {
    fprintf(f, "%d %d\n", n * n, 2 * (n-1) * n + (n-1) * (n-1) + n * n);

    int i, j;
    for (i=0; i< n; i++)
      for (j=0; j< n; j++) {
        double mid = -6;
        double side = 1;
	if (i > 0 && j > 0) {
	  fprintf(f, "%d ", (i-1) * n + j-1 + 1);
          fprintf(fv, "%lf ", side);
        }
	if (i > 0) {
	  fprintf(f, "%d ", (i-1) * n + j + 1);
          fprintf(fv, "%lf ", side);
        }
	if (j > 0) {
	  fprintf(f, "%d ", i * n + j-1 + 1);
          fprintf(fv, "%lf ", side);
        }

        fprintf(f, "%d ", i * n + j + 1);
        fprintf(fv, "%lf ", mid);

        if (j < n-1) {
	  fprintf(f, "%d ", i * n + j+1 + 1);
          fprintf(fv, "%lf ", side);
        }
        if (i < n - 1) {
          fprintf(f, "%d ", (i+1) * n + j + 1);
          fprintf(fv, "%lf ", side);
        }
	if (i < n-1 && j < n-1) {
	  fprintf(f, "%d ", (i+1) * n + j+1 + 1);
          fprintf(fv, "%lf ", side);
        }
	fprintf(f, "\n");

	fprintf(fp, "%d %d\n", i, j);
      }

  } else if (strcmp(argv[1], "m9p") == 0) {
    fprintf(f, "%d %d\n", n * n, 2 * (n-1) * n + 2 * (n-1) * (n-1) + n * n);

    int i, j;
    for (i=0; i< n; i++)
      for (j=0; j< n; j++) {
        double side = 1;
        double mid = -8;
	if (i > 0) {
	  fprintf(f, "%d ", (i-1) * n + j + 1);
          fprintf(fv, "%lf ", side);
        }
	if (i < n-1) {
	  fprintf(f, "%d ", (i+1) * n + j + 1);
          fprintf(fv, "%lf ", side);
        }
	if (j > 0) {
	  fprintf(f, "%d ", i * n + j-1 + 1);
          fprintf(fv, "%lf ", side);
        }
	if (j < n-1) {
	  fprintf(f, "%d ", i * n + j+1 + 1);
          fprintf(fv, "%lf ", side);
        }

        fprintf(f, "%d ", i * n + j + 1);
        fprintf(fv, "%lf ", mid);

        if (i > 0 && j > 0) {
	  fprintf(f, "%d ", (i-1) * n + j-1 + 1);
          fprintf(fv, "%lf ", side);
        }
	if (i < n-1 && j < n-1) {
	  fprintf(f, "%d ", (i+1) * n + j+1 + 1);
          fprintf(fv, "%lf ", side);
        }
	if (i > 0 && j < n-1) {
	  fprintf(f, "%d ", (i-1) * n + j+1 + 1);
          fprintf(fv, "%lf ", side);
        }
	if (i < n-1 && j > 0) {
	  fprintf(f, "%d ", (i+1) * n + j-1 + 1);
          fprintf(fv, "%lf ", side);
        }
	fprintf(f, "\n");

	fprintf(fp, "%d %d\n", i, j);
      }

  } else if (strcmp(argv[1], "cube") == 0) {
    fprintf(f, "%d %d\n", n * n * n, 3 * (n-1) * n * n + n * n * n);

    int i, j, k;
    for (i=0; i< n; i++)
      for (j=0; j< n; j++)
	for (k=0; k< n; k++) {
          double side = 1;
          double mid = -6;

          fprintf(f, "%d ", (i * n + j) * n + k + 1);
          fprintf(fv, "%lf ", mid);

          if (i > 0) {
	    fprintf(f, "%d ", ((i-1) * n + j) * n + k + 1);
            fprintf(fv, "%lf ", side);
          }
	  if (i < n-1) {
	    fprintf(f, "%d ", ((i+1) * n + j) * n + k + 1);
            fprintf(fv, "%lf ", side);
          }
	  if (j > 0) {
	    fprintf(f, "%d ", (i * n + j-1) * n + k + 1);
            fprintf(fv, "%lf ", side);
          }
	  if (j < n-1) {
	    fprintf(f, "%d ", (i * n + j+1) * n + k + 1);
            fprintf(fv, "%lf ", side);
          }
	  if (k > 0) {
	    fprintf(f, "%d ", (i * n + j) * n + k-1 + 1);
            fprintf(fv, "%lf ", side);
          }
	  if (k < n-1) {
	    fprintf(f, "%d ", (i * n + j) * n + k+1 + 1);
            fprintf(fv, "%lf ", side);
          }
	  fprintf(f, "\n");
	}

  } else {
    fprintf(stderr, "unknown graph type %s\n", argv[1]);
    exit(1);
  }

  fclose(f);
  fclose(fv);
  fclose(fp);

  return 0;
}
